### ISSUE TITLE
Container Build Engine

### ISSUE THREAD

**Issue by mrjamiek** [djcass44/ci-tools#2]
Hello, 

I ended up getting this to work with a little tweak to the tagging. ✌️

```yaml
com.github.Snakdy.container-build-engine:
    dockercfg: true
    command: container-build-engine
    args:
      - build
      - --image={{ .Image.Name }}
      {{- range $i, $e := .Tags }}
      - --tag={{ $e }} 
      {{- end }}
      {{- range $i, $e := .ExtraArgs }}
      - {{ $e }}
      {{- end }}
```
```bash
# Gets evaluated as:
container-build-engine build  \
--image=registry.com/group/project/ImageName  \
--tag=7186c76df373c7eb58cbd765b41751b354df0962  \
--tag=7186c76d  \
--tag=latest  \
--tag=main  \
--tag=main-7186c76-1717452330  \
--config=pipeline-ordered.yaml
```
